In [104]:
import pandas as pd
import numpy as np

In [105]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [106]:
df = pd.read_csv('CreditScoring.csv')
df.sample(10)

Status  Seniority  Home  Time  Age  Marital  Records  Job  Expenses  \
815        1          3     2    48   48        2        1    3        45   
95         1          3     2    36   41        2        1    3        75   
3839       1          2     5    60   24        1        1    1        35   
3157       1         13     3    60   40        2        1    1        60   
2933       1         28     2    24   49        2        1    1        35   
1212       2          4     5    60   38        4        1    1        35   
3355       1          0     2    60   56        2        1    1        45   
3864       1          8     2    12   39        2        1    1        75   
895        1          5     1    36   37        2        1    1        74   
2711       1          3     2    60   27        2        1    3        45   

      Income  Assets  Debt  Amount  Price  
815      100    4000     0    1600   2600  
95       200    3000     0    1000   1000  
3839     164       0     0     900   1516  
3157     100    3500   540     970   1270  
2933      73    2700     0     400    500  
1212     100       0     0    1300   1500  
3355     150   10000     0    1000   1798  
3864     160    1500     0     360    865  
895      138       0     0     900   1358  
2711      21    4000     0    1050   1064

In [107]:
df.columns = df.columns.str.lower()
df.columns

Index(['status', 'seniority', 'home', 'time', 'age', 'marital', 'records',
       'job', 'expenses', 'income', 'assets', 'debt', 'amount', 'price'],
      dtype='object')

In [108]:
df.status.unique()

array([1, 2, 0], dtype=int64)

Although most columns are numerical, some are categorical: status, home, marital, records and job. We need to translate them to their actual names

In [109]:
status_values = {
    1: 'ok',
    2: 'default',
    0: 'unk'
}

In [110]:
df.status = df.status.map(status_values)

In [111]:
df.sample(10)

status  seniority  home  time  age  marital  records  job  expenses  \
3057       ok         29     2    48   60        2        1    1        35   
3578  default         11     6    60   48        2        1    1        75   
959   default          1     5    36   33        1        1    1        35   
809   default          2     1    48   31        2        1    3       102   
3072  default          0     5    60   22        1        1    2        35   
1063       ok          3     2    24   46        2        1    3        75   
903        ok         13     2    60   40        2        1    1        90   
2685  default          1     2    60   40        2        1    3        35   
3466       ok          2     2    60   40        2        1    3        75   
1973  default          0     2    24   58        2        2    1        45   

      income  assets  debt  amount  price  
3057     152    3500     0    1050   1550  
3578     225       0     0    1300   1550  
959      125       0     0     600   1600  
809      268       0     0    1400   1635  
3072      49       0     0    1250   1316  
1063     500   14000     0     500   1095  
903      130    3000     0     800    860  
2685     349    6000  4000    1300   1511  
3466      67   25000     0    1800   2287  
1973     150    4000     0     600   1607

In [112]:
home_values = {
    1: 'rent',
    2: 'owner',
    3: 'private',
    4: 'ignore',
    5: 'parents',
    6: 'other',
    0: 'unk'
}

In [113]:
df.home = df.home.map(home_values)
df.sample(5)

status  seniority     home  time  age  marital  records  job  expenses  \
57         ok          4  parents    30   27        1        1    1        45   
2144  default          1  parents    60   22        1        1    1        35   
2807       ok          0    owner    18   26        1        1    4        35   
397   default          1  private    48   34        2        2    3        45   
2693       ok         10    other    42   26        1        1    1        35   

      income  assets  debt  amount  price  
57       100    5000     0     500   1048  
2144      45       0     0    1350   1520  
2807      85    7500  2600     600   1290  
397      200    3000  1500    1000   1191  
2693      67       0     0     800   1400

In [114]:
marital_values = {
    1: 'single',
    2: 'married',
    3: 'widow',
    4: 'separated',
    5: 'divorced',
    0: 'unk'
}

In [115]:
df.marital = df.marital.map(marital_values)
df.sample(5)

status  seniority     home  time  age  marital  records  job  expenses  \
473        ok          0    other    60   26  married        1    2        45   
3248       ok          1  parents    60   25  married        1    1        35   
833   default          1  parents    36   23   single        1    2        35   
4401       ok          1  private    60   24   single        1    1        35   
2991       ok          4    other    48   20   single        1    1        35   

      income  assets  debt  amount  price  
473       68       0     0    1200   1315  
3248     140       0     0    2000   2100  
833       75       0     0     350    425  
4401     174    7000  6500     950   1468  
2991     245       0     0    1126   1631

In [116]:
records_values = {
    1: 'no',
    2: 'yes',
    0: 'unk'
}

In [117]:
df.records = df.records.map(records_values)
df.sample(5)

status  seniority     home  time  age  marital records  job  expenses  \
1934     ok          3    owner    48   25   single      no    1        35   
1057     ok         14    owner    60   39  married      no    1       105   
281      ok          8  private    36   39  married      no    1        75   
894      ok         15     rent    60   37  married      no    1        58   
1770     ok          3     rent    48   51  married      no    3        90   

        income  assets  debt  amount  price  
1934       125    4000     0    1000   1301  
1057       129    3500  1200     750   1888  
281        128    2500     0     550    550  
894        134     500     0     900   1333  
1770  99999999       0     0    1200   1240

In [118]:
job_values = {
    1: 'fixed',
    2: 'parttime',
    3: 'freelance',
    4: 'others',
    0: 'unk'
}

In [119]:
df.job = df.job.map(job_values)
df.sample(5)

status  seniority     home  time  age  marital records        job  \
1757  default          0     rent    36   32  married      no  freelance   
1709       ok          4  parents    48   21   single      no      fixed   
137   default          1     rent    60   37   single      no      fixed   
3608       ok         28    owner    36   46  married      no      fixed   
4283       ok          0  parents    48   23   single      no      fixed   

      expenses  income  assets  debt  amount  price  
1757        89     285       0     0    1000   1304  
1709        35      88   25000     0    1100   1200  
137         45     100       0     0    1150   1555  
3608        75     170    6000     0     750    800  
4283        35      56       0     0     325   1202

In [120]:
df.describe().round()

seniority    time     age  expenses      income      assets  \
count     4455.0  4455.0  4455.0    4455.0      4455.0      4455.0   
mean         8.0    46.0    37.0      56.0    763317.0   1060341.0   
std          8.0    15.0    11.0      20.0   8703625.0  10217569.0   
min          0.0     6.0    18.0      35.0         0.0         0.0   
25%          2.0    36.0    28.0      35.0        80.0         0.0   
50%          5.0    48.0    36.0      51.0       120.0      3500.0   
75%         12.0    60.0    45.0      72.0       166.0      6000.0   
max         48.0    72.0    68.0     180.0  99999999.0  99999999.0   

             debt  amount    price  
count      4455.0  4455.0   4455.0  
mean     404382.0  1039.0   1463.0  
std     6344253.0   475.0    628.0  
min           0.0   100.0    105.0  
25%           0.0   700.0   1118.0  
50%           0.0  1000.0   1400.0  
75%           0.0  1300.0   1692.0  
max    99999999.0  5000.0  11140.0

The max value in income assets, etc is 99999999. It seems like an artificial value. Lets replace this big number with NaN for these respective columns

In [121]:
for c in ['income', 'assets', 'debt']:
    df[c] = df[c].replace(to_replace=99999999, value=np.nan)

In [122]:
df.describe().round()

seniority    time     age  expenses  income    assets     debt  amount  \
count     4455.0  4455.0  4455.0    4455.0  4421.0    4408.0   4437.0  4455.0   
mean         8.0    46.0    37.0      56.0   131.0    5403.0    343.0  1039.0   
std          8.0    15.0    11.0      20.0    86.0   11573.0   1246.0   475.0   
min          0.0     6.0    18.0      35.0     0.0       0.0      0.0   100.0   
25%          2.0    36.0    28.0      35.0    80.0       0.0      0.0   700.0   
50%          5.0    48.0    36.0      51.0   120.0    3000.0      0.0  1000.0   
75%         12.0    60.0    45.0      72.0   165.0    6000.0      0.0  1300.0   
max         48.0    72.0    68.0     180.0   959.0  300000.0  30000.0  5000.0   

         price  
count   4455.0  
mean    1463.0  
std      628.0  
min      105.0  
25%     1118.0  
50%     1400.0  
75%     1692.0  
max    11140.0

In [123]:
df.status.value_counts()

ok         3200
default    1254
unk           1
Name: status, dtype: int64

Notice that there is one row with "unknown" status: we don't know whether or not this client managed to pay back the loan. This row seems like it is not useful so let's remove it.

In [124]:
df = df[df.status != 'unk']

In [125]:
df.status.value_counts()

ok         3200
default    1254
Name: status, dtype: int64

Splitting the data

In [126]:
from sklearn.model_selection import train_test_split

In [127]:
df_train_full, df_test = train_test_split(df, test_size=0.2, random_state=11)

In [128]:
df_train_full

status  seniority     home  time  age  marital records        job  \
3669       ok         22    owner    48   48  married      no      fixed   
2540  default          8    other    60   41  married      no  freelance   
279        ok          2  parents    36   19  married      no      fixed   
3537       ok          1    owner    12   61  married      no     others   
3867       ok         13    owner    60   27  married      no      fixed   
...       ...        ...      ...   ...  ...      ...     ...        ...   
332   default          4    owner    60   47  married      no  freelance   
1293       ok          2     rent    60   28   single      no      fixed   
4024       ok          2  parents    36   25   single      no      fixed   
3776       ok          4    other    60   25   single      no      fixed   
1945  default          1  parents    48   25   single      no  freelance   

      expenses  income   assets   debt  amount  price  
3669        60   110.0   3000.0    0.0    1000   1460  
2540        45    62.0      0.0    0.0    1800   2101  
279         35   162.0   4000.0  100.0     400    570  
3537        45   103.0  20000.0    0.0     300    650  
3867        35   253.0   7000.0    0.0    1060   1750  
...        ...     ...      ...    ...     ...    ...  
332         75     0.0  13500.0    0.0    1900   1976  
1293        45   101.0      0.0    0.0    1300   1333  
4024        35   110.0      0.0    0.0     500   1200  
3776        35   162.0      0.0    0.0    1800   2999  
1945        35     0.0      0.0    0.0    1800   1809  

[3563 rows x 14 columns]

In [129]:
df_test

status  seniority   home  time  age  marital records        job  \
1207  default          3  owner    36   26   single      no  freelance   
1734       ok         10   rent    60   28  married      no      fixed   
3750       ok         14   rent    60   41  married      no      fixed   
4246       ok          4  owner    60   39  married      no  freelance   
2227  default          1  other    30   20   single      no      fixed   
...       ...        ...    ...   ...  ...      ...     ...        ...   
975        ok         19  owner    12   42  married      no      fixed   
1616       ok          7  owner    36   24  married      no      fixed   
1670       ok          0  owner    24   28  married      no   parttime   
1742  default          8  other    36   30  married     yes  freelance   
3049       ok          4  owner    24   49  married      no      fixed   

      expenses  income   assets    debt  amount  price  
1207        35     0.0  60000.0  3000.0     800   1000  
1734        78   325.0     18.0  3000.0    2250   2250  
3750        53   181.0      0.0     0.0    1150   2497  
4246        45     0.0   7500.0     0.0    1300   1508  
2227        35    90.0      0.0     0.0     450    500  
...        ...     ...      ...     ...     ...    ...  
975         90   464.0   5000.0     0.0    1100   2413  
1616        45    95.0   3000.0     0.0    1000   1597  
1670        45   219.0   6000.0     0.0     600    943  
1742        75   100.0   4000.0  1365.0    1220   1745  
3049        45   132.0  15000.0     0.0     850   1338  

[891 rows x 14 columns]

In [130]:
df_train, df_val = train_test_split(df_train_full, test_size=0.25, random_state=11)

In [131]:
len(df_train), len(df_val), len(df_test)

(2672, 891, 891)

In [132]:
y_train = (df_train.status == 'default').values
y_train

array([ True,  True, False, ..., False, False, False])

In [133]:
y_val = (df_val.status == 'default').values
y_val

array([False, False, False,  True, False,  True, False,  True, False,
       False, False,  True,  True, False,  True,  True, False,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True, False,  True, False, False, False, False, False,
        True,  True,  True,  True, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
        True,  True, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False,  True, False, False, False,  True,  True, False, False,
        True,  True, False, False, False,  True, False,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False,  True, False,  True, False,  True, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
        True,  True,

In [134]:
del df_train['status']
del df_val['status']

In [135]:
# from initial analysis, our data contains missing values-
# we added these NaNs ourselves. Replace the missing values
# with zero
df_train = df_train.fillna(0)
df_train

seniority     home  time  age  marital records        job  expenses  \
951          10    owner    36   36  married      no  freelance        75   
688           6  parents    48   32   single     yes      fixed        35   
2233          1  parents    48   40  married      no      fixed        75   
3304          1  parents    48   23   single      no   parttime        35   
2271          5    owner    36   46  married      no  freelance        60   
...         ...      ...   ...  ...      ...     ...        ...       ...   
2382         18  private    36   45  married      no      fixed        45   
1784          7  private    60   29  married      no      fixed        60   
808           1  parents    24   19   single      no      fixed        35   
1857         15    owner    48   43  married      no  freelance        60   
488          12    owner    48   27  married     yes      fixed        45   

      income   assets    debt  amount  price  
951      0.0  10000.0     0.0    1000   1400  
688     85.0      0.0     0.0    1100   1330  
2233   121.0      0.0     0.0    1320   1600  
3304    72.0      0.0     0.0    1078   1079  
2271   100.0   4000.0     0.0    1100   1897  
...      ...      ...     ...     ...    ...  
2382   220.0  20000.0     0.0     800   1600  
1784    51.0   3500.0   500.0    1000   1290  
808     28.0      0.0     0.0     400    600  
1857   100.0  18000.0     0.0    2500   2976  
488    110.0   5000.0  1300.0     450   1636  

[2672 rows x 13 columns]

In [136]:
df_val = df_val.fillna(0)
df_val

seniority     home  time  age    marital records        job  expenses  \
2404          6     rent    36   31  separated      no      fixed        49   
908          18     rent    60   38    married      no      fixed        56   
2464         17     rent    24   40    married     yes      fixed        58   
1663          2    other    48   29    married      no      fixed        75   
1518         25     rent    42   61    married      no      fixed        57   
...         ...      ...   ...  ...        ...     ...        ...       ...   
1968          0    owner    12   21     single      no      fixed        35   
4371         12    owner    60   45    married      no      fixed        75   
1324          2    owner    60   36    married     yes  freelance        60   
4081          3  parents    24   25     single     yes      fixed        35   
2935         15    owner    60   32   divorced      no  freelance        35   

      income   assets    debt  amount  price  
2404   140.0      0.0     0.0     550    999  
908    108.0      0.0     0.0    1000   1307  
2464   128.0      0.0     0.0     700    982  
1663    96.0   6000.0  3000.0    1200   1521  
1518   121.0      0.0     0.0     750    830  
...      ...      ...     ...     ...    ...  
1968   147.0   1500.0     0.0     350    350  
4371   131.0   5000.0     0.0    1150   1452  
1324   140.0  29000.0     0.0    3900   4812  
4081   128.0      0.0     0.0     300   1397  
2935     0.0   6000.0  3300.0    1550   1612  

[891 rows x 13 columns]

In [137]:
# to use categorical variables, we need to encode them. 
# use DictVectorizer from scikit-learn
# DictVectorizer needs a list of dictionaries, so first convert
# the dataframe into this format
dict_train = df_train.to_dict(orient='records')
dict_val = df_val.to_dict(orient='records')

In [138]:
from sklearn.feature_extraction import DictVectorizer

In [139]:
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(dict_train)
X_val = dv.transform(dict_val)

Decision trees

In [140]:
from sklearn.tree import DecisionTreeClassifier

In [141]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [142]:
from sklearn.metrics import roc_auc_score

In [143]:
y_pred = dt.predict_proba(X_train)[:, 1]
y_pred

array([1., 1., 0., ..., 0., 0., 0.])

In [144]:
roc_auc_score(y_train, y_pred)

1.0

In [145]:
# we see that the score is 100% - the perfect score.
# Let's check the score on validation before jumping to conclusions
y_pred = dt.predict_proba(X_val)[:, 1]
y_pred

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0.

In [147]:
roc_auc_score(y_val, y_pred)

0.6692529849119663

In [148]:
# Model is overfitting as the tree learned the training data so well
# that is simply memorized the outcome for each customer. However,
# when we applied it to the validation set, the model failed.

In [149]:
# change the depth of tree to make the model less complex
dt = DecisionTreeClassifier(max_depth=2)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2)

In [150]:
# to visualize the tree use export_text
from sklearn.tree import export_text
tree_text = export_text(dt, feature_names=dv.feature_names_)
print(tree_text)

|--- records=yes <= 0.50
|   |--- job=parttime <= 0.50
|   |   |--- class: False
|   |--- job=parttime >  0.50
|   |   |--- class: True
|--- records=yes >  0.50
|   |--- seniority <= 6.50
|   |   |--- class: True
|   |--- seniority >  6.50
|   |   |--- class: False



In [151]:
y_pred = dt.predict_proba(X_train)[:, 1]
auc = roc_auc_score(y_train, y_pred)
print('train auc', auc)

train auc 0.7054989859726213


In [152]:
y_pred = dt.predict_proba(X_val)[:, 1]
auc = roc_auc_score(y_val, y_pred)
print('validation auc', auc)

validation auc 0.6685264343319367
